### ISSUE TITLE
Using cors.Allow procedurally instead of in the middleware stack

### ISSUE THREAD

**Issue by ian-lewis-cs** [martini-contrib/cors#13]
The examples provided demonstrate using cors.Allow() in the Martini middleware stack.

In my case I am working on a router service which has a single handler as middleware and passes off the various actions in a procedural manner. 

Is it valid to do the following inside my handler:

``` golang
doCors := cors.Allow(&cors.Options{
    AllowOrigins:     permittedDomains,
})

doCors(response, request)
```

I've left out any additional logic.

Many thanks,
Ian

**Comment by vastbinderj** [comment]
If you want to re-write the Martini router....  

The second example in the readme demonstrates how to inject CORS before your Handler is called to respond to pre-flight requests for options.  

I would just inject it before your handler like so:

``` go
allowCORSHandler := cors.Allow(&cors.Options{
  AllowOrigins:     []string{"https://*.foo.com"},
  AllowMethods:     []string{"PUT", "PATCH"},
  AllowHeaders:     []string{"Origin"},
})

m.Put("/api/books", allowCORSHandler, func() string {
  // ...
})
```

**Comment by vastbinderj** [comment]
You know, CORS is not that complex, you could write your own CORS implementation.

**Comment by rakyll** [comment]
Like @vastbinderj said, you can add the cors handler to your handler chain, if you want it to set it globally for all routes.

Closing this issue, if this suggestion doesn't solve your problem, please reopen it.

**Comment by ian-lewis-cs** [comment]
Thanks for the help!
