### ISSUE TITLE
build status 'fail'

### ISSUE THREAD

**Issue by hariharan-uno** [martini-contrib/cors#20]
The wercker status has been showing the 'fail' state for quite some time now. I guess it was because of some machine error than an actual test failure. @rakyll can you rebuild it so that it won't deter any new visitors.

**Comment by hariharan-uno** [comment]
Sorry, I just noticed the wercker account is of @superlogical .

**Comment by jakejscott** [comment]
@hariharan-uno What do you need me to do? Sorry haven't really been helping out that much with martini-contrib

**Comment by hariharan-uno** [comment]
Don't worry. I did a workaround by sending an empty commit as a PR and it triggered the rebuild on that branch. Anyways, now the status is green. :)
