### ISSUE TITLE
Set error code 200 for OPTIONS requests

### ISSUE THREAD

**Issue by elwinar** [martini-contrib/cors#8]
`OPTIONS` requests ask for a set of headers to be sent with a `200 OK` code. This error code is not set by the middleware, so routing continue through the other middlewares and handlers, resulting in incorrect behavior.

For instance, if doing a Basic Auth check right after the CORS check, an `OPTIONS` request will get `401 Unauthorized` error code thus won't perform the call.

My solution is currently to add a catch-all for `OPTIONS` (see snipet below) with an empty handler, which will result in the correct error code being sent back (instead of 401, 404, etc).

---

``` go
m := martini.New()

m.Use(cors.Allow(&cors.Options{
    AllowAllOrigins: true,
    AllowMethods: []string{"GET"},
}))

r := martini.NewRouter()
r.Options("/**", func() { return })

// Other handlers

m.Action(r.Handle)

http.ListenAndServe(":"+strconv.Itoa(c.Port), m)
```

**Comment by rakyll** [comment]
I pushed 66f078ea4c64d183a8993a755c6aa4dad527d51f to return HTTP 200s for preflight requests. This should have fixed your problem.
